version: '3'

services:
  client:
    stdin_open: true # to fix bug in create-react-app
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  nginx:
    depends_on:
      - client
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3000:80'
